# Generated by Django 4.2 on 2023-04-27 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_friends',
            field=models.ManyToManyField(blank=True, through='users.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
