# Generated by Django 4.2 on 2023-04-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_my_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
